version: 2.1

orbs:
  node: circleci/node@5  # Use CircleCI's Node.js orb for easier configuration

jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      # Optionally uncomment and run tests if you have tests
      # - run:
      #     name: Run tests
      #     command: npm test --passWithNoTests

  build-node:
    # Build node project
    executor: node/default
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy build output to artifacts directory
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

 sonar-scan:
  # Run SonarQube scan
  executor: node/default
  working_directory: ~/project/frontend
  steps:
    - checkout:
        path: ~/project
    - node/install-packages:
        pkg-manager: npm
    - run:
        name: Install SonarQube Scanner locally
        command: npm install --save-dev sonar-scanner
    - run:
        name: Run SonarQube scan using npx
        command: |
          npx sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
    - run:
        name: Wait for SonarQube analysis to complete
        command: sleep 30  # Adjust wait time if necessary


workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
      - sonar-scan:
          requires:

            - build-node
